package com.rkade;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;

public class AxisPanel {
    private JLabel minLabel;
    private JTextField minText;
    private JLabel centerLabel;
    private JTextField centerText;
    private JProgressBar progress;
    private JLabel maxLabel;
    private JTextField maxText;
    private JTextField dzText;
    private JLabel valueLabel;
    private JTextField valueText;
    private JLabel rawLabel;
    private JTextField rawText;
    private JLabel deadZoneLabel;
    private JPanel mainPanel;

    public JComponent getRootComponent() {
        return mainPanel;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridBagLayout());
        mainPanel.setDoubleBuffered(false);
        mainPanel.setPreferredSize(new Dimension(1020, 100));
        mainPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Axis", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        minLabel = new JLabel();
        minLabel.setText("Min");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        mainPanel.add(minLabel, gbc);
        minText = new JTextField();
        minText.setPreferredSize(new Dimension(65, 30));
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        mainPanel.add(minText, gbc);
        centerLabel = new JLabel();
        centerLabel.setText("Center");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        mainPanel.add(centerLabel, gbc);
        centerText = new JTextField();
        centerText.setPreferredSize(new Dimension(65, 30));
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        mainPanel.add(centerText, gbc);
        progress = new JProgressBar();
        progress.setEnabled(false);
        progress.setFocusable(false);
        progress.setMaximum(1023);
        progress.setMinimum(0);
        progress.setName("Y Axis");
        progress.setPreferredSize(new Dimension(760, 29));
        progress.setValue(0);
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        mainPanel.add(progress, gbc);
        maxLabel = new JLabel();
        maxLabel.setHorizontalAlignment(2);
        maxLabel.setText("Max");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        mainPanel.add(maxLabel, gbc);
        maxText = new JTextField();
        maxText.setPreferredSize(new Dimension(65, 30));
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        mainPanel.add(maxText, gbc);
        deadZoneLabel = new JLabel();
        deadZoneLabel.setText("Deadzone");
        deadZoneLabel.setVerifyInputWhenFocusTarget(false);
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        mainPanel.add(deadZoneLabel, gbc);
        dzText = new JTextField();
        dzText.setPreferredSize(new Dimension(65, 30));
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        mainPanel.add(dzText, gbc);
        valueLabel = new JLabel();
        valueLabel.setPreferredSize(new Dimension(62, 17));
        valueLabel.setText("Value");
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        mainPanel.add(valueLabel, gbc);
        valueText = new JTextField();
        valueText.setPreferredSize(new Dimension(65, 30));
        gbc = new GridBagConstraints();
        gbc.gridx = 5;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        mainPanel.add(valueText, gbc);
        rawLabel = new JLabel();
        rawLabel.setPreferredSize(new Dimension(62, 17));
        rawLabel.setText("Raw");
        gbc = new GridBagConstraints();
        gbc.gridx = 6;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        mainPanel.add(rawLabel, gbc);
        rawText = new JTextField();
        rawText.setPreferredSize(new Dimension(65, 30));
        gbc = new GridBagConstraints();
        gbc.gridx = 7;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        mainPanel.add(rawText, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

}
