package com.rkade;

import javax.swing.*;
import java.awt.*;

public class GainPanel {
    private JTextField gainText;
    private JLabel gainPercent;
    private JSlider gainSlider;
    private JPanel gainPanel;
    private JLabel labelText;
    private short gainIndex;

    public short getGainIndex() {
        return gainIndex;
    }

    public void setGainIndex(short gainIndex) {
        this.gainIndex = gainIndex;
    }

    public void setGainLabel(String label) {
        labelText.setText(label);
    }

    public JTextField getGainText() {
        return gainText;
    }

    public JSlider getGainSlider() {
        return gainSlider;
    }

    public void setGainAmount(int amount) {
        gainSlider.setValue(amount);
        gainText.setText(String.valueOf(amount));
        double percent = ((double) amount / (double) 1024) * 100;
        gainPercent.setText(String.format("%.1f%%", percent));
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        gainPanel = new JPanel();
        gainPanel.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        gainPanel.setMinimumSize(new Dimension(562, 41));
        labelText = new JLabel();
        labelText.setHorizontalAlignment(2);
        labelText.setMinimumSize(new Dimension(105, 17));
        labelText.setPreferredSize(new Dimension(105, 17));
        labelText.setText("");
        gainPanel.add(labelText);
        gainText = new JTextField();
        gainText.setText("1024");
        gainPanel.add(gainText);
        gainPercent = new JLabel();
        gainPercent.setEnabled(true);
        gainPercent.setText("100%");
        gainPanel.add(gainPercent);
        gainSlider = new JSlider();
        gainSlider.setMajorTickSpacing(128);
        gainSlider.setMaximum(2048);
        gainSlider.setMinimumSize(new Dimension(220, 31));
        gainSlider.setMinorTickSpacing(32);
        gainSlider.setName("");
        gainSlider.setPaintLabels(false);
        gainSlider.setPaintTicks(true);
        gainSlider.setPreferredSize(new Dimension(350, 31));
        gainSlider.setValue(1024);
        gainPanel.add(gainSlider);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return gainPanel;
    }

}
