package com.rkade;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;

public class MainForm implements DeviceListener, ActionListener {
    private final static String CENTER_BUTTON = "Set Center";
    private JPanel mainPanel;
    private JTabbedPane tabbedPane;
    private JPanel inputsPanel;
    private JPanel ffbPanel;
    private JPanel bottomPanel;
    private JComboBox<String> deviceComboBox;
    private JLabel firmwareLabel;
    private JComboBox<String> rangeComboBox;
    private JLabel rangeLabel;
    private JSlider wheelSlider;
    private JButton centerButton;
    private JTextField velocityText;
    private JTextField accText;
    private JLabel accLabel;
    private JLabel degreesLabel;

    public MainForm() {
        centerButton.addActionListener(this);
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        if (CENTER_BUTTON.equals(e.getActionCommand())) {

        }
    }

    @Override
    public void deviceAttached(Device device) {
        deviceComboBox.addItem(device.getName());
    }

    @Override
    public void deviceDetached(Device device) {
        deviceComboBox.removeItem(device.getName());
    }

    @Override
    public void deviceUpdated(Device device, String status, DataReport report) {
        if (status != null) {
            firmwareLabel.setText(status);
        }

        if (report != null) {
            if (report.getReportType() == DataReport.DATA_REPORT_ID) {
                List<Short> values = report.getValues();
                if (report instanceof WheelDataReport) {
                    WheelDataReport wheelData = (WheelDataReport) report;
                    //System.out.println(report);
                    String newRange = String.valueOf(wheelData.getRange());
                    String oldRange = (String) rangeComboBox.getSelectedItem();
                    if (!newRange.equals(oldRange)) {
                        rangeComboBox.removeAllItems();
                        rangeComboBox.addItem(newRange);
                    }
                    wheelSlider.setValue(wheelData.getValue());
                    wheelSlider.setToolTipText(String.valueOf(wheelData.getValue()));
                    velocityText.setText(String.valueOf(wheelData.getVelocity()));
                    accText.setText(String.valueOf(wheelData.getAcceleration()));
                    degreesLabel.setText(Math.round(wheelData.getAngle()) + "°");
                }
            }
        }
    }

    public JComponent getRootComponent() {
        return mainPanel;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridBagLayout());
        mainPanel.setPreferredSize(new Dimension(1024, 768));
        tabbedPane = new JTabbedPane();
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        mainPanel.add(tabbedPane, gbc);
        inputsPanel = new JPanel();
        inputsPanel.setLayout(new FlowLayout(FlowLayout.LEFT, 5, 5));
        tabbedPane.addTab("Inputs", inputsPanel);
        rangeComboBox = new JComboBox();
        inputsPanel.add(rangeComboBox);
        rangeLabel = new JLabel();
        rangeLabel.setText("Range");
        inputsPanel.add(rangeLabel);
        centerButton = new JButton();
        centerButton.setLabel("Set Center");
        centerButton.setPreferredSize(new Dimension(100, 30));
        centerButton.setText("Set Center");
        inputsPanel.add(centerButton);
        wheelSlider = new JSlider();
        wheelSlider.setEnabled(false);
        wheelSlider.setMajorTickSpacing(8192);
        wheelSlider.setMaximum(32768);
        wheelSlider.setMinimum(-32768);
        wheelSlider.setPaintLabels(true);
        wheelSlider.setPaintTicks(true);
        wheelSlider.setPaintTrack(true);
        wheelSlider.setPreferredSize(new Dimension(400, 40));
        wheelSlider.setSnapToTicks(false);
        wheelSlider.setValue(0);
        wheelSlider.setValueIsAdjusting(false);
        inputsPanel.add(wheelSlider);
        degreesLabel = new JLabel();
        degreesLabel.setHorizontalTextPosition(2);
        degreesLabel.setPreferredSize(new Dimension(54, 17));
        degreesLabel.setText("");
        inputsPanel.add(degreesLabel);
        final JLabel label1 = new JLabel();
        label1.setText("Velocity:");
        inputsPanel.add(label1);
        velocityText = new JTextField();
        velocityText.setPreferredSize(new Dimension(100, 30));
        inputsPanel.add(velocityText);
        accLabel = new JLabel();
        accLabel.setText("Acceleration:");
        inputsPanel.add(accLabel);
        accText = new JTextField();
        accText.setPreferredSize(new Dimension(100, 30));
        inputsPanel.add(accText);
        ffbPanel = new JPanel();
        ffbPanel.setLayout(new GridBagLayout());
        tabbedPane.addTab("Force Feedback", ffbPanel);
        bottomPanel = new JPanel();
        bottomPanel.setLayout(new FlowLayout(FlowLayout.LEFT, 5, 5));
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.SOUTH;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        mainPanel.add(bottomPanel, gbc);
        deviceComboBox = new JComboBox();
        deviceComboBox.setMinimumSize(new Dimension(200, 30));
        deviceComboBox.setPreferredSize(new Dimension(200, 30));
        bottomPanel.add(deviceComboBox);
        firmwareLabel = new JLabel();
        firmwareLabel.setText("Version 1.2");
        bottomPanel.add(firmwareLabel);
        label1.setLabelFor(velocityText);
        accLabel.setLabelFor(accText);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

}
